// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdxwecpgbvwjvgvbfyar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkeHdlY3BnYnZ3anZndmJmeWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzIzNjQsImV4cCI6MjA3MTgwODM2NH0.02YWsTAAEIoKAfDaxBRW7cmR336BPg0KsnOG0QXsRkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});